**Magic commands (Design to solve various common problem)**



**%timeit magic command** 

In [ ]:
%timeit [ i*j for i in range(4) for j in range(4)]

1000000 loops, best of 3: 1.84 µs per loop


**Some examples of IN and OUT keyword uses** 

In [ ]:
import math
print(math.sin(2))
print(math.cos(3))
print(In)


0.9092974268256817
-0.9899924966004454
['', "get_ipython().magic('paste')\ndef sum(a,b):\n  c=a+b\n  return c\nsum(5,3)", "get_ipython().magic('cpaste')\ndef sum(a,b):\n  c=a+b\n  return c\nsum(5,3)", "get_ipython().magic('cpaste')\nimport numpy as np\n\na = np.array([[1,2,3],[0,1,4]])\nb = np.zeros((2,3), dtype=np.int16)\nc = np.ones((2,3), dtype=np.int16)\nd = a + b + c\nprint(d[1,2])", "def sum(a,b):\n  c=a+b\n  return c\nsum(2,3)\nget_ipython().magic('run Numpy practice')", "def sum(a,b):\n  c=a+b\n  return c\nsum(2,3)\nget_ipython().magic('run Numpypractice')", "def sum(a,b):\n  c=a+b\n  return c\nsum(2,3)\nget_ipython().magic('run Numpypractice')", "def sum(a,b):\n  c=a+b\n  return c\nsum(2,3)\nget_ipython().magic('run Numpypractice.py')", "def sum(a,b):\n  c=a+b\n  return c\nsum(2,3)\nget_ipython().magic('run Numpypractice.ipynb')", "def sum(x):\n  return X**2\nsum(2)\nget_ipython().magic('run Numpypractice.ipynb')", "def sum(x):\n  return x**2\nsum(2)\nget_ipython().magic('run 

In [ ]:
def sq(n):
  return n**2
print(sq(5))

25


In [ ]:
print(Out)

{27: 12, 32: 15, 34: 12}


**Uses of underscore **

In [ ]:
print(_)

12


In [ ]:
print(__)

15


In [ ]:
%history

%paste
def sum(a,b):
  c=a+b
  return c
sum(5,3)
%cpaste
def sum(a,b):
  c=a+b
  return c
sum(5,3)
%cpaste
import numpy as np

a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d[1,2])
def sum(a,b):
  c=a+b
  return c
sum(2,3)
%run Numpy practice
def sum(a,b):
  c=a+b
  return c
sum(2,3)
%run Numpypractice
def sum(a,b):
  c=a+b
  return c
sum(2,3)
%run Numpypractice
def sum(a,b):
  c=a+b
  return c
sum(2,3)
%run Numpypractice.py
def sum(a,b):
  c=a+b
  return c
sum(2,3)
%run Numpypractice.ipynb
def sum(x):
  return X**2
sum(2)
%run Numpypractice.ipynb
def sum(x):
  return x**2
sum(2)
%run Numpypractice.ipynb
def sum(x):
  return x**2
sum(2)
%run Practice.ipynb
def sum(x):
  return x**2
sum(2)
%run Practice.py
def sum(x):
  return x**2
print(sum(2))
%run Practice.py
def sum(x):
  return x**2
print(sum(2))
%run Practice.ipynb
%timeit [ i*j for i in range(4) for j in range(4)]
import math
math.sin(2)
math.cos(3)
prin

Introduction to Numpy

In [1]:
#for create an array from list
import numpy as np
np.array([1,2,3],dtype="int64")

array([1, 2, 3])

In [ ]:
multiarray=np.array( [range(i,i+3) for i in [2,4,6]])
print(multiarray)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [ ]:
#create a length of 10 integer
np.zeros((1,2),dtype=int)

array([[0, 0]])

In [ ]:
#create 3*5 floating point array
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Full the matxic with one value
np.full((3,5),5)

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [ ]:
#use of arange 
np.arange(0,20,2)
type(np.arange(0,20,2))

numpy.ndarray

In [ ]:
# For evenly spaced 
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
#random value b/w 0 to 1
np.random.random((3,5))

array([[0.27206472, 0.71177254, 0.79278674, 0.64555035, 0.15775758],
       [0.38689183, 0.10133043, 0.11324674, 0.19092785, 0.1444322 ],
       [0.05025535, 0.23784008, 0.81699617, 0.94403776, 0.71978045]])

In [ ]:
np.random.normal(0,1,(3,3))

array([[ 0.82623177, -0.67535301, -0.04198735],
       [ 0.33835646, -0.6649019 , -0.20652141],
       [ 0.99640116,  0.53176375,  0.17202196]])

In [ ]:
#Random number in integer on  range
np.random .randint(1,10,(3,3))

array([[9, 1, 9],
       [5, 4, 4],
       [2, 2, 8]])

In [ ]:
#for identical matrix 
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#NUMPY Attributes 
np.random.seed(0)
X1=np.random.randint(10,size=6)
X2=np.random.randint(10,size=(3,3))
X3=np.random.randint(10,size=(3,4,5))
print(X3.ndim) #no of dimension
print(X3.shape) # total no of size of each dimension
print(X3.size) # total no of element
print(X3.dtype)


3
(3, 4, 5)
60
int64


Array indexing :Accessing single elements

In [ ]:
x2_sub=X2[:2,:2]
print(x2_sub)

[[3 5]
 [4 7]]


In [ ]:
#Copy() function use 
x2_sub_copy=X2[:2,:2].copy()
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 4  7]]


In [ ]:
#reshape : It is use to reshape the array
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Concatenation of Arrays

In [ ]:
x=np.array([1,2,3])
y=np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
grid=np.array([[1,2,3],
               [4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
grid=np.array([[1,2,3],
               [4,5,6]])
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

np.vstack() and np.hstack() Examples and uses 

In [ ]:
x=np.array([1,2,3,])
grid=np.array([[9,8,7],
               [6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
x=np.array([[1,2,3],
               [4,5,6]])
np.hstack([grid,x])

array([[9, 8, 7, 1, 2, 3],
       [6, 5, 4, 4, 5, 6]])

Splitting arrays (np.split,np.hsplit,np.vsplit)

In [ ]:
x=np.arange(0,20)
x1,x2=np.split(x,[10])
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]


In [ ]:
grid=np.arange(16).reshape((4,4))
upper,lower=np.vsplit(grid,[2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left,right=np.hsplit(grid,[2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Inverse the matrix

In [ ]:
x=np.arange(1,20,2).reshape(2,5)
x
y=1/x
y

array([[1.        , 0.33333333, 0.2       , 0.14285714, 0.11111111],
       [0.09090909, 0.07692308, 0.06666667, 0.05882353, 0.05263158]])

Airthmatical operation

In [ ]:
x=np.arange(4)
y=np.arange(5,9)
x//2
np.add(x,2)
np.subtract(x,1)
np.negative(x)
np.multiply(x,y)


array([ 0,  6, 14, 24])

In [ ]:
x=np.array([-1,2,-3,-4])
np.abs(x) # or we can also use np.absolute

array([1, 2, 3, 4])

Trignometric function

In [ ]:
theta=np.linspace(0,np.pi,3)
print("Theta",theta)
print(np.sin(theta))

Theta [0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]


In [ ]:
x=[-1,0,1]
print(np.arcsin(x))
print(np.arccos(x))

[-1.57079633  0.          1.57079633]
[3.14159265 1.57079633 0.        ]


Exponents and Logareithms

In [ ]:
x=np.arange(1,10)
print(np.exp(x))
print(np.log(x))
print(np.log10(x))

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [ ]:
x=np.arange(5)
y=np.empty(5)
print(np.multiply(x,10,out=y))
y=np.zeros(10)
np.power(2,x,out=y[::2])

[ 0. 10. 20. 30. 40.]


array([ 1.,  2.,  4.,  8., 16.])

In [ ]:
#Aggregate score
print(np.add.reduce(x))
x=np.array([1,2,3,4,5])
print(np.multiply.reduce(x))
#To store indermidiate result
np.add.accumulate(x)
#Outer products
np.multiply.outer(x,x)

15
120


array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

Aggerations Min,max and Everything in between.


In [ ]:
np.random.seed(0)
l=np.random.random(100)
np.sum(l)
sum(l)
l.sum()
#similary we can use it max,min

47.279383951251766

In [ ]:
m=np.random.randint(1,100,(3,4))
print(m.min(axis=0)) # to know minmum value in every coloum
print(m.min(axis=1)) # to know min value in every row

[ 3  4 27 20]
[ 3 14 27]


aggeregation of nan function
np.nansum(),np.nanprod(),np.nanmean()

Computation of array Brodcasting

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [ ]:

b=np.arange(1,9).reshape(2,4).transpose()
b


array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
np.ones((3,3))+ np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
#Example 1
M=np.ones((2,3))
a=np.arange(3)
M+a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
#Example 2
M=np.ones((3,2))
a=np.arange(3)[:,np.newaxis]
M+a

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

Broadcasting in practice

In [ ]:
#centring on array
x=np.random.random((10,3))
xmean=x.mean(0) #mean near zero value
xmean
x_centred=x-xmean
x_centred.mean(0) #mean near zero value

array([ 1.22124533e-16, -3.33066907e-17, -2.22044605e-17])

In [ ]:
#Plotting a two dimensional functions
x=np.linspace(0,5,50)
y=np.linspace(0,5,50)[:,np.newaxis]
z=np.sin(x)**10+np.cos(10+y*x)*np.cos(x)
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])

Comparision Operators as Ufuncs ( np.equal,np.not_equal,np.less,np.less_equal,np.greater,np.greater_equal)

In [ ]:
x=np.array([1,2,3,4,5])
x<3  # or np.less(x,3)

array([ True,  True, False, False, False])

In [ ]:
#Two 2d array
rng=np.random.RandomState(0)
x=rng.randint(10,size=(3,4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
#working with boolean 
np.count_nonzero(x<6)
np.sum(x<6)

8

In [ ]:
np.sum(x<6,axis=1)

array([4, 2, 2])

In [ ]:
#are there any value greater than 8
np.any(x>8)

True

In [ ]:
# all value are less than 8
np.all(x<8,axis=1)

array([ True, False,  True])

Boolean operators

In [ ]:
#Bitwise logic operators we can also use np.bitwise_and ,np.bitwise_or,np.bitwise_xor ,np.bitwise_not
np.sum((x>5) & (x<8)) #If we use and , or then it give value error 

3

In [ ]:
A=np.array([1,0,1,0,0,1,1],dtype=bool)
B=np.array([1,1,1,0,0,1,1],dtype=bool)
A|B # if we use or then it will give valueError

array([ True,  True,  True, False, False,  True,  True])

Fancy Indexing (for fast result)

In [ ]:
rand=np.random.RandomState(0)
x=rand.randint(100,size=10)
ind=[3,4,5]
x[ind]

array([67, 67,  9])

In [5]:
x=np.arange(12).reshape((3,4))
row=np.array([0,1,2]) # It simply maps the row and column data
col=np.array([2,1,3]) # It simply maps the row and column data
print(x[row,col])
print(x)


[ 2  5 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
x[row[:,np.newaxis],col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

In [8]:
# Combined indexes
x[2,[2,0,1]]

array([10,  8,  9])

In [9]:
x[0:,[0,2,1]]

array([[ 0,  2,  1],
       [ 4,  6,  5],
       [ 8, 10,  9]])

In [16]:
mean=[0,0]
cov=[[1,2],
     [2,5]]
rand=np.random.RandomState(43)
x=rand.multivariate_normal(mean,cov,100)
x.shape
x

array([[ 1.09854270e-01, -7.18121548e-01],
       [ 5.54394610e-01,  7.59438515e-01],
       [-6.34704324e-01, -1.97935057e+00],
       [-1.22953618e+00, -7.92538945e-01],
       [-9.98651684e-01, -2.88636118e+00],
       [ 1.45823588e-01,  8.44883733e-01],
       [ 1.87154916e+00,  3.58520474e+00],
       [-4.07817567e-01, -1.11911455e+00],
       [-1.55116505e+00, -4.41424121e+00],
       [ 1.30759503e+00,  2.19389851e+00],
       [ 4.85750914e-02, -5.68101535e-02],
       [-1.90784866e+00, -5.03795384e+00],
       [-3.88661950e-01,  1.87185505e-02],
       [-1.12860557e-01,  3.28915178e-01],
       [-6.85230650e-01, -7.48108942e-01],
       [ 9.91559239e-01,  3.26824567e+00],
       [ 5.61272855e-02,  3.38103895e-01],
       [-2.77664925e-01,  1.12539898e+00],
       [ 1.35574984e+00,  4.78767945e+00],
       [ 4.22035024e-02,  1.75684985e+00],
       [-1.51667572e+00, -2.56296345e+00],
       [-1.63236501e+00, -1.48786020e+00],
       [ 7.72109588e-01,  1.23487583e+00],
       [ 2.

In [21]:
# Select random 20 number 
y=np.arange(21)
indices = np.random.choice(y,20,replace=False)
indices
selection=y[indices]
selection

array([ 8,  5, 11, 12, 17, 10, 18, 15, 16, 19,  0,  6, 20,  2, 14, 13,  4,
        3,  1,  9])

In [51]:
#Sorting Of array
x=np.array([(2,1,4,3,5)])
%timeit np.sort(x)
%timeit x.sort()


The slowest run took 21.53 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.37 µs per loop
The slowest run took 63.23 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 269 ns per loop


In [57]:
x=np.array([(2,1,4,3,5)])
i=np.argsort(x) # it reurn index of sorted one array
i


array([[1, 0, 3, 2, 4]])

In [62]:
# for 2D array
np.random.seed(0)
x=np.random.randint(1,10,(3,3))
np.sort(x,axis=1)

array([[1, 4, 6],
       [4, 4, 8],
       [3, 5, 6]])

In [66]:
#partitioning of array
x=np.array([7,4,6,8,9,2,1])
np.partition(x,3) #All elements smaller than the k-th element are moved before this element and all equal or greater are moved behind it. 
                #The ordering of the elements in the two partitions is undefined.

array([1, 2, 4, 6, 7, 9, 8])